version: '3'
services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "80:80"
    depends_on:
      - user_service

  user_service:
    build: ./user_service
    ports:
      - "8001:8000"
